### ISSUE TITLE
safe delete issue

### ISSUE THREAD

**Issue by sabrinaslattery** [Qarik-Group/safe#232]
Trying to delete a key in my app's secret that has a typo in it - unfortunately it contains a colon. How can I use `safe delete pathway:keyname` when my keyname includes a colon?

So far have tried a combination of: containing the keyname in double quotes, single quotes, and with a backslash in front of the colon in the keyname. None of these have worked. 

Thank you!

**Comment by thomasmitchell** [comment]
The colon issue was a little more widespread than just the `delete` command. This, along with some other oddities around escaping colons and carets, have now been addressed in v1.8.0. tldr; you can prepend the `:` with a `\`... like `\:`, and safe will now treat it like a normal, non-separating colon.
